typography_spectrum: 0.4058430902659893
color:
  brandStrength: 0.33934462489560246
  lightness: 0.41564473137259483
  saturation: 0.9771871995180845
  rhythmicContrast: 0.5408572887536138
  brandColors:
    - '#FFFFFF'
    - '#A78081'
    - '#624F51'
    - '#E9BCB6'
    - '#332D2D'
opengraph:
  type: 'https://www.facebook.com/villadigitalaprendiendo/'
layout_spectrum: 0.2907046349719167
author:
  name: Alvaro Villalobos
  email: alvill04@hotmail.com
name: Vistadigital
navigation:
  - name: Consultor
    url: 'https://www.facebook.com/villadigitalaprendiendo/'
    type: external
title: Pensando en personas
description: Gente
